# Makefile for CS 520 using glsl
# T.L. Yu, Feb. 2009

PROG = tests1
TOP = /pool/u/class/cs520/Mesa-7.0.3
include $(TOP)/configs/current

INCDIR = -I$(TOP)/../glew/include
#INCDIR = $(TOP)/include -I$(TOP)/../glew/include

LIBS = -L$(TOP)/lib -l$(GLUT_LIB) -l$(GLU_LIB) -l$(GL_LIB) $(APP_LIB_DEPS) -L$(TOP)/../glew/lib -lGLEW 

#source codes
SRCS = $(PROG).cpp
#substitute .cpp by .o to obtain object filenames
OBJS = $(SRCS:.cpp=.o)

CC=g++

$(PROG): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) $(LIBS) -o $@

$(OBJS): $(SRCS) 
	$(CC) -c $*.cpp $(INCDIR)

run:
	export LD_LIBRARY_PATH=$(TOP)/lib; ./$(PROG)  

clean:
	-rm  $(OBJS)  *~
